{
    "message": "Access granted.",
    "acc_ledger_entry": [
        {
            "id": "5028",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "106_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5029",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "106_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5030",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "106_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5031",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "106_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5032",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "81_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5033",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "81_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5034",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "81_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5035",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "81_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5036",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "71_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5037",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "71_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5038",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "71_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5039",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "71_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5040",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "88_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5041",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "88_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5042",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "88_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5043",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "88_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:25:53"
        },
        {
            "id": "5044",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "106_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5045",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "106_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5046",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "106_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5047",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "106_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5048",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "81_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5049",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "81_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5050",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "81_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5051",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "81_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5052",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "71_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5053",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "71_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5054",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "71_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5055",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "71_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5056",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "88_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5057",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "88_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5058",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "88_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5059",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "88_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:28:22"
        },
        {
            "id": "5060",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "106_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5061",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "106_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5062",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "106_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5063",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "106_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5064",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "81_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5065",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "81_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5066",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "81_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5067",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "81_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5068",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "71_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5069",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "71_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5070",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "71_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5071",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "71_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5072",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "88_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "9_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5073",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "9_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "88_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "5",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5074",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "88_STU_4",
            "grp_ref_code": "1003_4",
            "ledger_folio": "1_LDR_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "DR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        },
        {
            "id": "5075",
            "school_id": "4",
            "school_name": "Jyoti Public Senior Sec. School",
            "sch_medium": "English",
            "ldr_ref_id": "1_LDR_4",
            "grp_ref_code": "1002_4",
            "ledger_folio": "88_STU_4",
            "cost_center": "50",
            "entry_month": "6",
            "op_balance": "",
            "op_type": "",
            "tr_amount": "45",
            "tr_type": "CR",
            "cl_balance": "",
            "cl_type": "",
            "session_year_id": "1",
            "server_date_time": "2020-10-28 04:29:09"
        }
    ]
}
